ARCM: Updating Auto-Resp Control Module as per the changes in FMAN driver.
FMAN driver has changed its AR structure field's name to fix the ENGR00324489
which was causing compilation error in Auto Response Control Module. So ARCM
needs to be updated as per the current implemetation.

Change-Id: I1f7dfd2997dc53cc9f744046bdece40dcdc3887d
CR:ENGR00325120
Signed-off-by: Sunil Kumar Kori <Sunil.Kori@freescale.com>
Reviewed-on: http://git.am.freescale.net:8181/15284
Reviewed-by: Rajan Gupta <rajan.gupta@freescale.com>
Tested-by: Rajan Gupta <rajan.gupta@freescale.com>